name: Java Spring Boot Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar Código del Repositorio
      uses: actions/checkout@v4

    - name: 2. Instalar Máquina Virtual Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: 3. Descargar Librerías de Maven y Compilar Código Fuente
      run: mvn clean compile

    - name: 4. Ejecutar Pruebas Unitarias Integradas
      run: mvn test

    - name: 5. Empaquetar el archivo binario JAR de Producción
      run: mvn package -DskipTests

    - name: 6. Construir Imagen Docker Reactiva
      run: docker build -t RobValdes01/java-gateway:latest -f Dockerfile.java .
